package com.example.Library1.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Lob;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;


@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class CatalogItem {
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private int itemId;
    private String titleName;
    private String author;
    private int quantity;
    private String price;
    private String description;
    private String genre;
    
    @Lob
    @Column(columnDefinition ="LONGTEXT")
    private String image;
    
//	 @OneToMany(fetch = FetchType.LAZY)
////	    @JoinColumn(name = "job_id")
//	    private Cart cart;

    // Getters and setters are generated by Lombok
}

